---
- name: configur and restart telegraf service
  hosts: all
  gather_facts: yes
  tasks:
    - name: Ensure telegraf service is restarted
      win_service:
        name: telegraf
        state: absent
