---
- name: configur and restart telegraf service
  hosts: all
  gather_facts: yes
  tasks:
    - name: Install Telegraf as a service using win_command
      ansible.windows.win_command:
        cmd: 'C:\Program Files\InfluxData\telegraf\telegraf-1.33.0\telegraf.exe --service install --config C:\Program Files\\InfluxData\telegraf\telegraf-1.33.0\telegraf.conf'
    
    - name: Ensure telegraf service is restarted
      win_service:
        name: telegraf
        start_mode: auto
        state: started
