---
- name: Install and configure Telegraf on Windows
  hosts: all
  tasks:
    - name: Download Telegraf installer
      ansible.windows.win_get_url:
        url: https://dl.influxdata.com/telegraf/releases/telegraf-1.33.0_windows_amd64.zip
        dest: C:\\Windows\\Temp\\telegraf.zip

    - name: Extract Telegraf ZIP
      community.windows.win_unzip:
        src: C:\Windows\Temp\telegraf.zip
        dest: C:\Program Files\InfluxData\telegraf\
        remote_src: true


    - name: Download telegraf.conf from GitHub
      ansible.windows.win_get_url:
        url: https://raw.githubusercontent.com/natty98282/ansible-playbook-repo/master/Agent_installation/telegraf.conf
        dest: C:\\Program Files\\InfluxData\\telegraf\\telegraf-1.33.0\\telegraf.conf

    - name: Install Telegraf as a service using win_command
      ansible.windows.win_command:
        command: '"C:\\Program Files\\InfluxData\\telegraf\\telegraf-1.33.0\\telegraf.exe" --service install --config "C:\\Program Files\\InfluxData\\telegraf\\telegraf-1.33.0\\telegraf.conf"'

    - name: Start Telegraf service
      ansible.windows.win_service:
        name: telegraf
        state: started
        start_mode: auto