---
- name: Install and configure Telegraf on Windows
  hosts: all
  tasks:
    - name: Download Telegraf installer
      ansible.windows.win_get_url:
        url: https://dl.influxdata.com/telegraf/releases/telegraf-1.33.0_windows_amd64.zip
        dest: C:\Telegraf_installation\telegraf.zip

    - name: Extract Telegraf ZIP
      ansible.windows.win_unzip:
        src: C:\Telegraf_installation\telegraf.zip
        dest: C:\Program Files\InfluxData\telegraf\
        remote_src: true

    - name: Copy Telegraf files to root installation directory
      ansible.windows.win_shell:
        command: |
          cd C:\Program Files\InfluxData\telegraf\telegraf-1.33.0
          copy telegraf.* C:\Program Files\InfluxData\telegraf

    - name: Download telegraf.conf from GitHub
      ansible.windows.win_get_url:
        url: https://github.com/natty98282/ansible-playbook-repo/blob/master/Agent_installation/telegraf.conf
        dest: C:\Program Files\InfluxData\telegraf\

    - name: Install Telegraf as a Windows Service
      ansible.windows.win_shell:
        command: |
          C:\Program Files\InfluxData\telegraf\telegraf.exe --service install --config "C:\Program Files\InfluxData\telegraf\telegraf.conf"

    - name: Start Telegraf service
      ansible.windows.win_service:
        name: telegraf
        state: started
        start_mode: auto