---
- name: Install Windos Exporter agent on Windows and restart service
  hosts: all
  gather_facts: yes
  tasks:
    - name: Download Windows Exporter agent MSI
      win_get_url:
        url: "https://github.com/prometheus-community/windows_exporter/releases/download/v0.30.0/windows_exporter-0.30.0-amd64.msi"
        dest: "C:\\Windows\\Temp\\windows_exporter-0.30.0-amd64.msi"
    
    - name: Install Windows Exporter agent
      win_package:
        path: "C:\\Windows\\Temp\\windows_exporter-0.30.0-amd64.msi"
        arguments: 'ENABLED_COLLECTORS=iis,os,cpu,memory'
        state: present
    
    - name: Clean up the MSI installer
      win_file:
        path: "C:\\Windows\\Temp\\windows_exporter-0.30.0-amd64.msi"
        state: absent

    - name: Ensure Windows Exporter service is started
      win_service:
        name: windows_exporter
        start_mode: auto
        state: restarted
